// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200812114537_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("Domain.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Channels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e13a5d25-fe9a-4948-bf0b-96540bade182"),
                            Description = "Canal dedicado a dotnet core",
                            Name = "DotNetCore"
                        },
                        new
                        {
                            Id = new Guid("92e683a9-cc71-456d-ac5d-a779f86f21ff"),
                            Description = "Canal dedicado a Angular",
                            Name = "Angular"
                        },
                        new
                        {
                            Id = new Guid("c0bc4445-1ff2-4474-bf3d-491876ee3e62"),
                            Description = "Canal dedicado a ReactJs",
                            Name = "Reactjs"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
